### ISSUE TITLE
Migration file created in the vendor folder

### ISSUE THREAD

**Issue by shooteram** [BitBagCommerce/SyliusAdyenPlugin#70]
hello 👋 

https://github.com/BitBagCommerce/SyliusMolliePlugin/issues/101
^I've got a similar issue since I installed this package. When I generate a migration file, it seems to go in the vendor directory. 

```sh
$ bin/console d:m:diff
[...]
  Generated new migration class to "/Users/user/project/vendor/bitbag/sylius-adyen-plugin/src/DependencyInjection/../Migrations/Version20220912091140.php"
 
  To run just this migration for testing purposes, you can use migrations:execute --up 'BitBag\\SyliusAdyenPlugin\\Migrations\\Version20220912091140'
 
  To revert the migration you can use migrations:execute --down 'BitBag\\SyliusAdyenPlugin\\Migrations\\Version20220912091140'
```

My `config/packages/doctrine_migrations.yaml`:
```yaml
doctrine_migrations:
    storage:
        table_storage:
            table_name: sylius_migrations
    migrations_paths:
        'App\Migrations': "%kernel.project_dir%/src/Migrations"
```
